name: Swap Slots

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  swap-slots:
    runs-on: ubuntu-latest

    steps:
      - name: Swap Staging to Production
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
          az functionapp deployment slot swap --name ${{ env.AZURE_FUNCTIONAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --slot staging
