# This is a basic workflow to help you get started with the CI/CD for Functions Project
   
name: Build and Deploy Job
   
on:
  push:
    branches: ["main"]
 
  pull_request: 
    branches: [main]
 
  workflow_dispatch:
   
env:
  AZURE_FUNCTIONAPP_NAME: 'myfuncappagain'   # set this to your function app name on Azure
  PYTHON_VERSION: '3.9' # Set this to 3.9
   
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Code'
        uses: actions/checkout@v4

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 'Resolve Project Dependencies Using Pip'
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: 'Run Azure Functions Again'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: .
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          scm-do-build-during-deployment: true
          enable-oryx-build: true
